version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: formly_postgres
    environment:
      POSTGRES_USER: formly_user
      POSTGRES_PASSWORD: formly_password
      POSTGRES_DB: formly_db
    ports:
      - "5433:5432"
    volumes:
      - formly_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: formly_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: formly@example.com
      PGADMIN_DEFAULT_PASSWORD: formly_admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  formly_pgdata:
