import { BlockType } from "@/types";

export const formBlocks: Partial<BlockType>[] = [
  {
    id: "1",
    type: "statement",
    label: "Statement",
    text: "Hey there 😊",
    color: "bg-pink-200",
    icon: "💬",
    titleLabel: "Title",
    titleDefaultValue: "Hey there 😀",
    defaultButtonText: "Let's start",
    description: `Primarily used as "Intro" or "Welcome" block (like in the screenshot below), but can be used anywhere in your form to display a message.`,
  },
  {
    id: "2",
    type: "shortText",
    label: "Short Text",
    text: "this is short",
    color: "bg-blue-300",
    icon: "=",
    titleLabel: "Question",
    titleDefaultValue: "",
    defaultButtonText: "Next",
    defaultPlaceholder: "Your answer here...",
    description: `Use this for short answers, such as Name, Email Address, or any other short text answer.`,
  },
  {
    id: "3",
    type: "longText",
    label: "Long Text",
    text: "",
    color: "bg-yellow-300",
    icon: "≡",
    titleLabel: "Question",
    titleDefaultValue: "",
    defaultButtonText: "Next",
    defaultPlaceholder: "Your answer here...",
    description: `Use this if you want people to write longer answers. For e.g User Feedback, Full address etc.`,
  },
  {
    id: "4",
    type: "number",
    label: "Number",
    text: "Please enter a number",
    color: "bg-gray-400",
    icon: "#",
    titleLabel: "Question",
    titleDefaultValue: "Please enter a number",
    defaultButtonText: "Next",
    defaultPlaceholder: "",
    description: `Ask users to enter a numeric value.`,
  },
  {
    id: "5",
    type: "websiteUrl",
    label: "Website URL",
    text: "Please enter a URL",
    color: "bg-teal-300",
    icon: "🔗",
    titleLabel: "Question",
    titleDefaultValue: "Please enter a URL",
    defaultButtonText: "Next",
    defaultPlaceholder: "https://",
    description: `Ask users to enter a website URL for e.g their LinkedIn profile or their portfolio website.`,
  },
  {
    id: "6",
    type: "single",
    label: "Single Select Option",
    text: "Single Select Option",
    parentType: "select",
    color: "bg-pink-200",
    icon: "🔲",
    titleLabel: "Question",
    titleDefaultValue: "Which do you prefer? 👇",
    defaultButtonText: "Next",
    description: `Single Select Option blocks are used in questions where multiple options are presented to users but they can choose only one out of many. For e.g the following situation:`,
  },
  {
    id: "7",
    type: "multi",
    label: "Multi Select Option",
    parentType: "select",
    text: "Which do you prefer? 🤔",
    color: "bg-green-300",
    icon: "✓",
    titleLabel: "Question",
    titleDefaultValue: "Please choose at least one option 👇",
    defaultButtonText: "Next",
    description: `Unlike Single Select Option blocks, these blocks are used in questions where multiple options are presented to users and they can choose more than one among them. For e.g the following situation:`,
  },
  {
    id: "8",
    type: "dropdown",
    label: "Dropdown List",
    parentType: "select",
    text: "Please choose at least ...",
    color: "bg-red-300",
    icon: "🔽",
    titleLabel: "Question",
    titleDefaultValue: "Please choose 👇",
    defaultButtonText: "Next",
    description:
      "Use this block when you have large list of options to choose from. For example: What state do you live in?",
  },
  {
    id: "9",
    type: "date",
    label: "Date",
    text: "Please select a date",
    color: "bg-teal-400",
    icon: "📅",
    titleLabel: "Question",
    titleDefaultValue: "Please select a date",
    defaultButtonText: "Next",
    description: "Allows users to select a date.",
  },
  {
    id: "10",
    type: "address",
    label: "Address",
    text: "Please enter your complete address",
    color: "#b9cfe8",
    icon: "📍",
    titleLabel: "Question",
    titleDefaultValue: "Please enter your complete address",
    defaultButtonText: "Next",
    description: "",
  },
];
